name: Daily Commit

on:
  schedule:
    - cron: '30 1 * * *'
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name 'quang06091988'
          git config --global user.email 'quang06091988@gmail.com'

      - name: Create empty commit
        run: |
          git commit --allow-empty -m "🕒 Daily commit to keep GitHub active"

      - name: Push commit
        run: |
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
